import os

DEBUG = os.getenv('DEBUG', True)
SECRET_KEY = os.getenv('SECRET_KEY')
#SQLALCHEMY_DATABASE_URI = os.getenv('SQLALCHEMY_DATABASE_URI')
SQLALCHEMY_DATABASE_URI = "postgresql://postgres:SU39vobwhhLAIFpUdJ01@127.0.0.1/catalog_db"
SQLALCHEMY_TRACK_MODIFICATIONS = os.getenv('SQLALCHEMY_TRACK_MODIFICATIONS', True)
SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY')
LANGUAGES = ['en', 'uk_UA']
BABEL_TRANSLATION_DIRECTORIES = os.getenv('BABEL_TRANSLATION_DIRECTORIES')