import os

DEBUG = os.getenv( 'DEBUG', False )
SECRET_KEY = os.getenv( 'SECRET_KEY' )
SQLALCHEMY_DATABASE_URI = os.environ['DATABASE_URL']
SQLALCHEMY_TRACK_MODIFICATIONS = os.getenv( 'SQLALCHEMY_TRACK_MODIFICATIONS', False )
LANGUAGES = ['en', 'uk_UA']